export const SELECT_COMPONENT = 'SELECT_COMPONENT';
export const ADD_CHILD = 'ADD_CHILD';
export const EMBED_IN_COMPONENT = 'EMBED_IN_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';

export const EXERCISE_LAYOUT = 'EXERCISE_LAYOUT';

export const FLEX_SET_DIRECTION = 'FLEX_SET_DIRECTION';
export const FLEX_SET_DISTRIBUTION = 'FLEX_SET_DISTRIBUTION';
export const FLEX_SET_SPACING = 'FLEX_SET_SPACING';

export const INSET_SET_INSETS = 'INSET_SET_INSETS';

export const SOURCE_SET_SOURCE = 'SOURCE_SET_SOURCE';

export const SET_OBS_CONNECTION_STATE = 'SET_OBS_CONNECTION_STATE';
export const SET_OBS_SOURCES = 'SET_OBS_SOURCES';
export const SET_OBS_SCENES = 'SET_OBS_SCENES';

export const layoutExercisingMutations = [
  ADD_CHILD,
  EMBED_IN_COMPONENT,
  DELETE_COMPONENT,
  FLEX_SET_DIRECTION,
  FLEX_SET_DISTRIBUTION,
  FLEX_SET_SPACING,
  INSET_SET_INSETS,
  SOURCE_SET_SOURCE,
];
